name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "43 7 * * 0"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 8.3.1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache Bazel build artifacts
        uses: actions/cache@v3
        with:
          path: ~/.cache/bazel
          key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD.bazel', '**/WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-bazel-
      - name: Build
        run: "bazel build //..."
      - name: Test
        run: "bazel test //..."

